version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:latest
    restart: always
    ports:
      - "3166:3000"
    environment:
      # Using the libpq format. Notice the single quotes around the password variable!
      PGRST_DB_URI: host=db port=5432 dbname=${DB_NAME} user=${DB_USER} password='${DB_PASSWORD}'
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${DB_USER} 
    depends_on:
      - db

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "3165:8978" 
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - db

volumes:
  pgdata:
  cloudbeaver_data:
